import Link from 'next/link';
import { notFound } from 'next/navigation';
import { requireUser } from '@/lib/auth';
import { connectionStatus } from '@/lib/chatgpt-plan';
import { getAlertCase, getCaseTimeline } from '@/lib/case-service';
import { db } from '@/lib/db';
import { customerName, date, dateTime, money, title } from '@/lib/format';
import { investigationSchema } from '@/lib/validation';
import { Badge } from '@/components/badge';
import { CaseActions, Assignment } from '@/components/case-actions';
import { InvestigationView } from '@/components/investigation-view';
import { CaseViewAudit } from '@/components/case-view-audit';
import { ArrowLeft, UserRound, Landmark, History, ShieldAlert, ListChecks, Clock3, CircleCheck } from 'lucide-react';

export default async function AlertDetailPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ version?: string }> }) {
  const user = await requireUser();
  const id = (await params).id;
  const alert = await getAlertCase(id, user.organizationId);
  if (!alert) notFound();
  const [history, previousAlerts, timeline, analysts] = await Promise.all([
    db.transaction.findMany({ where: { organizationId: user.organizationId, customerId: alert.customerId, timestamp: { lt: alert.transaction.timestamp } }, orderBy: { timestamp: 'desc' }, take: 8 }),
    db.alert.findMany({ where: { organizationId: user.organizationId, customerId: alert.customerId, id: { not: id } }, orderBy: { createdAt: 'desc' }, take: 5 }),
    getCaseTimeline(id, user.organizationId),
    db.user.findMany({ where: { organizationId: user.organizationId, active: true, role: { in: ['ADMIN', 'MANAGER', 'ANALYST'] } }, select: { id: true, name: true }, orderBy: { name: 'asc' } }),
  ]);
  const requestedVersion = Number((await searchParams).version);
  const investigation = alert.investigations.find(i => i.version === requestedVersion) || alert.investigations[0];
  const parsed = investigation ? investigationSchema.safeParse(investigation.output) : null;
  const output = parsed?.success ? parsed.data : null;
  const name = customerName(alert.customer);
  const canWrite = user.role !== 'VIEWER';
  const plan = await connectionStatus(user.id);
  const customerTenureMonths = Math.max(0, Math.floor((alert.createdAt.getTime() - (alert.customer.onboardedAt ?? alert.customer.createdAt).getTime()) / 86400_000 / 30));
  return <div className="content"><CaseViewAudit alertId={id}/><div className="page-head"><div><Link href="/alerts" className="subtle" style={{ display: 'inline-flex', alignItems: 'center', gap: 5, fontSize: 11, marginBottom: 14 }}><ArrowLeft size={13}/> Back to alerts</Link><div className="eyebrow">TRANSACTION ALERT · {alert.id}</div><h1 style={{ display: 'flex', alignItems: 'center', gap: 10 }}>Alert investigation <Badge value={alert.status}/></h1><div className="subtle">{alert.type} · Created {dateTime(alert.createdAt)} · {name}</div></div><div className="button-row"><a className="button" href={`/api/alerts/${id}/export/pdf`}>Export report</a></div></div>
    <div className="case-grid">
      <div className="stack"><section className="card section-pad"><h3 className="section-title"><UserRound/> Customer profile</h3><div className="profile-name"><span className="avatar">{name.split(' ').map(v => v[0]).join('').slice(0, 2)}</span><span><strong>{name}</strong><small>{alert.customer.type === 'BUSINESS' ? 'Business customer' : 'Individual customer'} · {alert.customer.id.replace('demo-customer-', 'CUS-')}</small></span></div><dl className="detail-list"><dt>KYC status</dt><dd><Badge value={alert.customer.kycStatus}/></dd><dt>Risk rating</dt><dd><Badge value={alert.customer.riskRating}/></dd><dt>Country</dt><dd>{alert.customer.country}</dd><dt>Customer since</dt><dd>{date(alert.customer.onboardedAt ?? alert.customer.createdAt)}</dd><dt>Customer tenure at alert</dt><dd>{customerTenureMonths} months</dd><dt>{alert.customer.type === 'BUSINESS' ? 'Industry' : 'Occupation'}</dt><dd>{alert.customer.businessIndustry || alert.customer.occupation || 'Unknown'}</dd><dt>Source of funds</dt><dd>{alert.customer.sourceOfFunds || 'Unknown'}</dd><dt>Expected monthly volume</dt><dd>{alert.customer.expectedMonthlyVolume ? money(Number(alert.customer.expectedMonthlyVolume), alert.customer.expectedMonthlyVolumeCurrency) : 'Unknown'}</dd></dl><div className="divider"/><h3 className="section-title"><Landmark/> Linked accounts <span className="muted">({alert.customer.accounts.length})</span></h3>{alert.customer.accounts.map(account => <div key={account.id} className="note-box" style={{ marginBottom: 7 }}><strong>{account.displayName} ····{account.lastFour || '—'}</strong><br/>{account.institutionName || 'Unknown institution'} · {title(account.type)} · {account.status}</div>)}<div className="divider"/><h3 className="section-title"><History/> Previous alerts <span className="muted">({previousAlerts.length})</span></h3>{previousAlerts.length ? previousAlerts.map(a => <div key={a.id} style={{ display: 'flex', justifyContent: 'space-between', fontSize: 10, marginTop: 10 }}><Link href={`/alerts/${a.id}`} className="table-link">{a.type}</Link><span className="muted">{date(a.createdAt)}</span></div>) : <div className="note-box">No previous alerts in this workspace.</div>}</section></div>
      <div className="stack"><section className="card"><div className="card-header"><h2 style={{ display: 'flex', alignItems: 'center', gap: 8 }}><ShieldAlert size={16} color="#c07a4a"/> Alert summary</h2><Badge value={alert.severity}/></div><div className="section-pad"><p style={{ fontSize: 12, lineHeight: 1.65, marginBottom: 16 }}>{alert.description}</p><div className="note-box"><strong>Why it was flagged</strong><br/>{alert.type}. Review the transaction against customer activity and available evidence before making a decision.</div></div></section>
        <section className="card"><div className="card-header"><h2 style={{ display: 'flex', alignItems: 'center', gap: 8 }}><Landmark size={16} color="#5b8c6a"/> Triggering transaction</h2><span className="muted" style={{ fontSize: 10 }}>{alert.transaction.id}</span></div><div className="section-pad"><div className="transaction-amount">{money(Number(alert.transaction.amount), alert.transaction.currency)} <small>{alert.transaction.currency}</small></div><div className="subtle" style={{ fontSize: 11, marginBottom: 19 }}>{title(alert.transaction.direction)} {title(alert.transaction.type)} · {dateTime(alert.transaction.timestamp)}</div><dl className="detail-list two-col" style={{ columnGap: 35 }}><dt>Counterparty</dt><dd>{alert.transaction.counterpartyName || 'Unknown'}</dd><dt>Destination country</dt><dd>{alert.transaction.counterpartyCountry || 'Unknown'}</dd><dt>Payment rail</dt><dd>{alert.transaction.paymentRail || title(alert.transaction.type)}</dd><dt>Status</dt><dd>{title(alert.transaction.status)}</dd><dt>Description</dt><dd>{alert.transaction.description || 'None recorded'}</dd>{alert.transaction.walletAddress && <><dt>Wallet</dt><dd style={{ overflowWrap: 'anywhere' }}>{alert.transaction.walletAddress}</dd></>}</dl></div></section>
        <section className="card"><div className="card-header"><div><h2 style={{ display: 'flex', alignItems: 'center', gap: 8 }}><History size={16} color="#5b8c6a"/> Transaction history</h2><small>Most recent activity before this alert</small></div></div><div className="table-wrap"><table><thead><tr><th>Date</th><th>Type</th><th>Counterparty</th><th>Direction</th><th>Amount</th></tr></thead><tbody>{history.map(t => <tr key={t.id}><td>{date(t.timestamp)}</td><td>{title(t.type)}</td><td>{t.counterpartyName || 'Unknown'}</td><td>{title(t.direction)}</td><td style={{ fontWeight: 700 }}>{money(Number(t.amount), t.currency)}</td></tr>)}</tbody></table></div></section>
        {investigation && <section className="card section-pad" style={{ padding: '12px 20px' }}><span className="muted" style={{ fontSize: 10 }}>Investigation versions: </span>{alert.investigations.map(item => <Link key={item.id} className={`button small ${item.id === investigation.id ? 'primary' : ''}`} style={{ marginLeft: 6 }} href={`/alerts/${id}?version=${item.version}`}>v{item.version}</Link>)}</section>}
        {output && investigation ? <InvestigationView output={output} evidence={investigation.evidence.map(e => ({ id: e.id, referenceId: e.referenceId, label: e.label, value: e.value, type: e.type, source: e.source }))} version={investigation.version} source={investigation.source} completedAt={investigation.completedAt.toISOString()}/> : <section className="card section-pad"><h3 className="section-title"><ListChecks/> Investigation</h3><div className="empty-state"><strong>No investigation yet</strong>Run an investigation to see structured risk factors, mitigating factors, and evidence.</div></section>}
      </div>
      <div className="stack"><section className="card section-pad"><h3 className="section-title"><ShieldAlert/> Risk assessment</h3><div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'baseline' }}><span className="subtle" style={{ fontSize: 11 }}>Risk score</span><strong style={{ fontSize: 27, letterSpacing: '-.04em' }}>{alert.riskScore}<small style={{ color: '#9baa9f', fontSize: 11 }}>/100</small></strong></div><div className="risk-track" style={{ width: '100%', height: 7, margin: '9px 0 16px' }}><div className={`risk-fill ${alert.riskScore >= 70 ? 'high' : ''}`} style={{ width: `${alert.riskScore}%` }}/></div><dl className="detail-list"><dt>Severity</dt><dd><Badge value={alert.severity}/></dd><dt>Status</dt><dd><Badge value={alert.status}/></dd></dl>{output && <><div className="divider"/><div className="eyebrow">RECOMMENDED NEXT STEP</div><div style={{ fontSize: 12, fontWeight: 700, marginBottom: 6 }}>{title(output.recommended_action)}</div><div className="subtle" style={{ fontSize: 10 }}>{output.recommendation_reasoning}</div></>}</section>
        <CaseActions alertId={id} status={alert.status} canWrite={canWrite} source={investigation?.source} aiEnabled={Boolean(process.env.OPENAI_DATA_SHARING_ENABLED === 'true' && (process.env.OPENAI_API_KEY || plan.model))}/>
        <section className="card section-pad"><h3 className="section-title"><UserRound/> Assignment</h3>{user.role === 'ADMIN' || user.role === 'MANAGER' ? <Assignment alertId={id} current={alert.assignedAnalystId} analysts={analysts}/> : <div className="subtle" style={{ fontSize: 11 }}>{alert.assignedAnalyst?.name || 'Unassigned'}</div>}</section>
        {alert.decisions.length > 0 && <section className="card section-pad"><h3 className="section-title"><CircleCheck/> Human decision</h3>{alert.decisions.map(d => <div key={d.id} className="note-box" style={{ marginBottom: 8 }}><strong>{title(d.decision)}</strong> · {d.analyst.name}<br/><span className="muted">{dateTime(d.createdAt)}</span><p style={{ margin: '8px 0 0' }}>{d.note}</p>{d.agreedWithAi !== null && <small>{d.agreedWithAi ? 'Agreed with' : 'Different from'} AI recommendation</small>}</div>)}</section>}
        <section className="card section-pad"><h3 className="section-title"><Clock3/> Audit activity</h3>{timeline.slice(0, 8).map(event => <div key={event.id} className="timeline-item"><div className="timeline-dot"/><div><strong>{title(event.action)}</strong><small>{dateTime(event.timestamp)}</small></div></div>)}{!timeline.length && <div className="subtle" style={{ fontSize: 10 }}>Case opened for review.</div>}<Link href="/audit-log" className="table-link" style={{ fontSize: 10 }}>View full audit log →</Link></section>
      </div>
    </div></div>;
}
