'use client';
import { useState } from 'react';
import type { InvestigationOutput } from '@/lib/validation';
import { Badge } from './badge';
import { title } from '@/lib/format';
import { Sparkles, ShieldCheck, CircleHelp, ArrowUpRight, ChevronRight } from 'lucide-react';

type Evidence = { id: string; referenceId: string; label: string; value: string; type: string; source: string };
export function InvestigationView({ output, evidence, version, source, completedAt }: { output: InvestigationOutput; evidence: Evidence[]; version: number; source: string; completedAt: string }) {
  const [selected, setSelected] = useState<string[] | null>(null);
  const relevant = selected?.map(id => evidence.find(item => item.referenceId === id)).filter((x): x is Evidence => !!x) ?? [];
  return <section className="card"><div className="card-header"><div><h2 style={{ display: 'flex', alignItems: 'center', gap: 8 }}><Sparkles size={16} color="#4b8662"/> Investigation analysis</h2><small>Version {version} · {source === 'CHATGPT_PLAN' ? 'ChatGPT plan output' : source === 'OPENAI' ? 'OpenAI structured output' : 'Synthetic demo output'} · {new Date(completedAt).toLocaleString('en-US')}</small></div><Badge value={output.confidence.toUpperCase()}/></div><div className="section-pad">
    <div className="insight"><div className="insight-head"><Sparkles/> CASE SUMMARY</div><p>{output.summary}</p></div>
    <div className="two-col" style={{ marginTop: 21 }}><div><h3 className="section-title" style={{ marginBottom: 8 }}><ArrowUpRight/> Risk factors <span className="muted" style={{ fontWeight: 400 }}>({output.risk_factors.length})</span></h3>{output.risk_factors.map((factor, index) => <button className={`factor ${selected === factor.evidence_ids ? 'selected' : ''}`} key={index} onClick={() => setSelected(factor.evidence_ids)}><strong>{factor.title}<Badge value={factor.severity.toUpperCase()}/></strong><p>{factor.explanation}</p><span style={{ display: 'inline-flex', alignItems: 'center', gap: 3, color: '#397b54', fontSize: 9, marginTop: 7 }}>{factor.evidence_ids.length} evidence item{factor.evidence_ids.length === 1 ? '' : 's'} <ChevronRight size={11}/></span></button>)}{!output.risk_factors.length && <p className="subtle" style={{ fontSize: 10 }}>No supported risk factors in this analysis.</p>}</div><div><h3 className="section-title" style={{ marginBottom: 8 }}><ShieldCheck/> Mitigating factors <span className="muted" style={{ fontWeight: 400 }}>({output.mitigating_factors.length})</span></h3>{output.mitigating_factors.map((factor, index) => <button className="factor" key={index} onClick={() => setSelected(factor.evidence_ids)}><strong>{factor.title}</strong><p>{factor.explanation}</p><span style={{ display: 'inline-flex', alignItems: 'center', gap: 3, color: '#397b54', fontSize: 9, marginTop: 7 }}>{factor.evidence_ids.length} evidence item{factor.evidence_ids.length === 1 ? '' : 's'} <ChevronRight size={11}/></span></button>)}{!output.mitigating_factors.length && <p className="subtle" style={{ fontSize: 10 }}>No mitigating factors identified.</p>}</div></div>
    {selected && <div className="evidence-drawer"><div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}><strong style={{ fontSize: 11 }}>Supporting evidence</strong><button className="button ghost small" onClick={() => setSelected(null)}>Close</button></div>{relevant.map(item => <div className="evidence-item" key={item.id}><strong>{item.label} <span className="muted">· {title(item.type)}</span></strong>{item.value}<br/><span className="muted">Source: {item.source}</span></div>)}</div>}
    <div className="two-col" style={{ marginTop: 22 }}><div><h3 className="section-title"><CircleHelp/> Missing information</h3>{output.missing_information.map((item, i) => <div className="note-box" key={i} style={{ marginTop: 8 }}><strong style={{ color: '#4b614f' }}>{item.field}</strong><br/>{item.reason_needed}</div>)}{!output.missing_information.length && <div className="subtle" style={{ fontSize: 10 }}>None identified.</div>}</div><div><h3 className="section-title">Behavioral anomalies</h3>{output.behavioral_anomalies.map((item, i) => <div className="note-box" key={i} style={{ marginTop: 8 }}><strong>{item.title}</strong><br/>{item.explanation}</div>)}{!output.behavioral_anomalies.length && <div className="subtle" style={{ fontSize: 10 }}>None identified.</div>}</div></div>
  </div></section>;
}
