import Link from 'next/link';
import { requireUser } from '@/lib/auth';
import { db } from '@/lib/db';
import { PageHeading } from '@/components/page-heading';
import { Badge } from '@/components/badge';
import { StatCard } from '@/components/stat-card';
import { customerName, date, money } from '@/lib/format';
import { Activity, CircleAlert, ShieldAlert, ScanSearch, ArrowRight } from 'lucide-react';
export default async function OverviewPage() { const user = await requireUser(); const org = user.organizationId; const [alerts, total, open, escalated, investigations] = await Promise.all([db.alert.findMany({ where: { organizationId: org }, include: { customer: true, transaction: true }, orderBy: [{ riskScore: 'desc' }, { createdAt: 'desc' }], take: 6 }), db.alert.count({ where: { organizationId: org } }), db.alert.count({ where: { organizationId: org, status: 'OPEN' } }), db.alert.count({ where: { organizationId: org, status: 'ESCALATED' } }), db.investigation.count({ where: { organizationId: org } })]); return <div className="content"><PageHeading eyebrow="OPERATIONS OVERVIEW" title={`Good day, ${user.name.split(' ')[0]}`} description="A clear view of the cases that need your attention." actions={<Link href="/alerts" className="button primary">Open alert queue <ArrowRight size={14}/></Link>}/><div className="stats-grid"><StatCard label="Total alerts" value={total} foot="Across the workspace" icon={Activity}/><StatCard label="Open alerts" value={open} foot="Awaiting review" icon={CircleAlert}/><StatCard label="Escalated" value={escalated} foot="Additional review needed" icon={ShieldAlert}/><StatCard label="Investigations" value={investigations} foot="Versioned case analyses" icon={ScanSearch}/></div><div className="card"><div className="card-header"><div><h2>Priority alerts</h2><small>Highest risk scores in the current queue</small></div><Link href="/alerts" className="table-link">View all →</Link></div><div className="table-wrap"><table><thead><tr><th>Alert</th><th>Customer</th><th>Type</th><th>Transaction</th><th>Severity</th><th>Status</th><th>Created</th></tr></thead><tbody>{alerts.map(a => <tr key={a.id}><td><Link className="table-link" href={`/alerts/${a.id}`}>{a.id}</Link></td><td>{customerName(a.customer)}</td><td>{a.type}</td><td>{money(Number(a.transaction.amount), a.transaction.currency)}</td><td><Badge value={a.severity}/></td><td><Badge value={a.status}/></td><td>{date(a.createdAt)}</td></tr>)}</tbody></table></div></div></div>; }
